version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  execute:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./app.py
          name: Execute

workflows:
  main:
    jobs:
      - execute
