version: 2.1

orbs:
  python: circleci/python@0.2.1
  dropbox: rascaltwo/dropbox-orb@dev:alpha


workflows:
  main:
    jobs:
      - download-previous:
          context: dropbox-context
      - execute:
          requires:
            - download-previous
      - upload-latest:
          context: dropbox-context
          requires:
            - execute

jobs:
  download-previous:
    executor: dropbox/default
    steps:
      - attach_workspace:
          at: ~/project
      - dropbox/download:
          downloadpath: /appending.csv
          filepath: ./appending.csv
      - persist_to_workspace:
          root: ~/project
          paths:
            - appending.csv
  execute:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./app.py
          name: Execute
      - persist_to_workspace:
          root: ~/project
          paths:
            - appending.csv
  upload-latest:
    executor: dropbox/default
    steps:
      - attach_workspace:
          at: ~/project
      - dropbox/upload:
          uploadpath: /appending.csv
          filepath: ./appending.csv
